name: "PostHog CI Metrics"
description: "Track workflow duration, success rates, and CI performance in PostHog"
author: "PostHog"
branding:
  icon: "activity"
  color: "orange"
inputs:
  posthog-token:
    description: 'Your PostHog API token - see project settings section "Project API Key"'
    required: true
  posthog-api-host:
    description: "Your PostHog API host"
    required: false
    default: "https://us.i.posthog.com"
  event:
    description: 'The event name to capture (e.g., "ci-metrics")'
    required: false
  properties:
    description: "Properties to add to the event - as a JSON string. Must be possible to `JSON.parse(properties)`"
    required: false
  capture-run-duration:
    description: "Capture run duration via GitHub API (adds duration_seconds and run metadata)"
    required: false
    default: "false"
  capture-job-durations:
    description: "Capture timing and status for each job in the workflow (emits one event per job)"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for API access (required for capture-run-duration, capture-job-durations, and status-job)"
    required: false
  runner:
    description: "Optional runner label to include in properties (e.g., 'depot')"
    required: false
  status-job:
    description: "Job name to check for workflow status (e.g., 'Django Tests Pass'). Captures that job's conclusion."
    required: false
  annotation:
    description: "Create a PostHog annotation with the provided text (e.g., 'Deployed to production')"
    required: false
  annotation-scope:
    description: "Annotation scope: 'project' (default) or 'organization'"
    required: false
    default: "project"
runs:
  using: "node20"
  main: "dist/index.js"
