on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test that this works
    steps:
      - name: Push an event to PostHog
        uses: pauldambra/posthog-github-action@0.0
        with:
          posthog-token: 'Mona the Octocat'
          event: 'gh-actions-test-emitting-from-actions'
